In [2]:
import pandas as pd

In [3]:
titanic_data = pd.read_csv("E:/DS -Python/Titanic_Data.csv", sep="\t")

In [12]:
titanic_data.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [13]:
titanic_data.tail()

PassengerId  Survived  Pclass                               Name     Sex  \
151          152         1       1  Pears, Mrs. Thomas (Edith Wearne)  female   
152          153         0       3                   Meo, Mr. Alfonzo    male   
153          154         0       3    van Billiard, Mr. Austin Blyler    male   
154          155         0       3              Olsen, Mr. Ole Martin    male   
155          156         0       1        Williams, Mr. Charles Duane    male   

      Age  SibSp  Parch      Ticket     Fare Cabin Embarked  
151  22.0      1      0      113776  66.6000    C2        S  
152  55.5      0      0  A.5. 11206   8.0500   NaN        S  
153  40.5      0      2    A/5. 851  14.5000   NaN        S  
154   NaN      0      0   Fa 265302   7.3125   NaN        S  
155  51.0      0      1    PC 17597  61.3792   NaN        C

In [15]:
# to work with specific columns only. retrieving some columns. for Single column you just put in single square braket
# but if you want to select multiple columns then you need to put 2 square bracket.
# ### if you find the data type of the single column it will display as Series (it has properties like List) 
# but when you check the type of multiple columns it will be data frame.

titanic_data['Sex'].head()   # always keep a note of upper case and lower case of the columns / values

0      male
1    female
2    female
3    female
4      male
Name: Sex, dtype: object

In [18]:
type(titanic_data['Sex'])   # the type will be series as there is only one column like a one dimension. same if you 
                            # one row then also it is a series

pandas.core.series.Series

In [20]:
titanic_data[['PassengerId','Name','Pclass','Sex']].head(6)  # always put the list of columns in squar braket.
                                                            # if you put a single columne within 2 square bracket then it will
                                                            # show as data frame only.

PassengerId                                               Name  Pclass  \
0            1                            Braund, Mr. Owen Harris       3   
1            2  Cumings, Mrs. John Bradley (Florence Briggs Th...       1   
2            3                             Heikkinen, Miss. Laina       3   
3            4       Futrelle, Mrs. Jacques Heath (Lily May Peel)       1   
4            5                           Allen, Mr. William Henry       3   
5            6                                   Moran, Mr. James       3   

      Sex  
0    male  
1  female  
2  female  
3  female  
4    male  
5    male

In [19]:
type(titanic_data[['PassengerId','Pclass','Name','Sex']])   # this will be dataframe

pandas.core.frame.DataFrame

In [23]:
titanic_data.dtypes   # to find the data types for each column we use dtypes. d types is a function

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

In [24]:
titanic_data.dtypes  == 'object'  

PassengerId    False
Survived       False
Pclass         False
Name            True
Sex             True
Age            False
SibSp          False
Parch          False
Ticket          True
Fare           False
Cabin           True
Embarked        True
dtype: bool

In [28]:
titanic_data.dtypes[titanic_data.dtypes  == 'object'] # retrieving only those dtypes which have dtypes == object

Name        object
Sex         object
Ticket      object
Cabin       object
Embarked    object
dtype: object

In [4]:
titanic_data.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [29]:
titanic_data.index

RangeIndex(start=0, stop=156, step=1)

In [33]:
a= titanic_data.dtypes[titanic_data.dtypes  == 'object'].index  # retrieves the index value and the column is diplayed 
                                                            # assigning a variable which holds columns which is object

In [36]:
titanic_data[a]

Name     Sex  \
0                              Braund, Mr. Owen Harris    male   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female   
2                               Heikkinen, Miss. Laina  female   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female   
4                             Allen, Mr. William Henry    male   
5                                     Moran, Mr. James    male   
6                              McCarthy, Mr. Timothy J    male   
7                       Palsson, Master. Gosta Leonard    male   
8    Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female   
9                  Nasser, Mrs. Nicholas (Adele Achem)  female   
10                     Sandstrom, Miss. Marguerite Rut  female   
11                            Bonnell, Miss. Elizabeth  female   
12                      Saundercock, Mr. William Henry    male   
13                         Andersson, Mr. Anders Johan    male   
14                Vestrom, Miss. Hulda Amanda Adolfina  female   
15                    Hewlett, Mrs. (Mary D Kingcome)   female   
16                                Rice, Master. Eugene    male   
17                        Williams, Mr. Charles Eugene    male   
18   Vander Planke, Mrs. Julius (Emelia Maria Vande...  female   
19                             Masselmani, Mrs. Fatima  female   
20                                Fynney, Mr. Joseph J    male   
21                               Beesley, Mr. Lawrence    male   
22                         McGowan, Miss. Anna "Annie"  female   
23                        Sloper, Mr. William Thompson    male   
24                       Palsson, Miss. Torborg Danira  female   
25   Asplund, Mrs. Carl Oscar (Selma Augusta Emilia...  female   
26                             Emir, Mr. Farred Chehab    male   
27                      Fortune, Mr. Charles Alexander    male   
28                       O'Dwyer, Miss. Ellen "Nellie"  female   
29                                 Todoroff, Mr. Lalio    male   
..                                                 ...     ...   
126                                McMahon, Mr. Martin    male   
127                          Madsen, Mr. Fridtjof Arne    male   
128                                  Peter, Miss. Anna  female   
129                                 Ekstrom, Mr. Johan    male   
130                               Drazenoic, Mr. Jozef    male   
131                     Coelho, Mr. Domingos Fernandeo    male   
132     Robins, Mrs. Alexander A (Grace Charity Laury)  female   
133      Weisz, Mrs. Leopold (Mathilde Francoise Pede)  female   
134                     Sobey, Mr. Samuel James Hayden    male   
135                                 Richard, Mr. Emile    male   
136                       Newsom, Miss. Helen Monypeny  female   
137                        Futrelle, Mr. Jacques Heath    male   
138                                Osen, Mr. Olaf Elon    male   
139                                 Giglio, Mr. Victor    male   
140                      Boulos, Mrs. Joseph (Sultana)  female   
141                           Nysten, Miss. Anna Sofia  female   
142  Hakkarainen, Mrs. Pekka Pietari (Elin Matilda ...  female   
143                                Burke, Mr. Jeremiah    male   
144                         Andrew, Mr. Edgardo Samuel    male   
145                       Nicholls, Mr. Joseph Charles    male   
146       Andersson, Mr. August Edvard ("Wennerstrom")    male   
147                   Ford, Miss. Robina Maggie "Ruby"  female   
148           Navratil, Mr. Michel ("Louis M Hoffman")    male   
149                  Byles, Rev. Thomas Roussel Davids    male   
150                         Bateman, Rev. Robert James    male   
151                  Pears, Mrs. Thomas (Edith Wearne)  female   
152                                   Meo, Mr. Alfonzo    male   
153                    van Billiard, Mr. Austin Blyler    male   
154                              Olsen, Mr. Ole Martin    male   
155                     

In [ ]:
# describe() fuction gives you information related to categorical data only if you have selected the columns relating to 
# categorical data otherwise by default it selects only those columns which have numerical data
#  Count - gives you the number of counts for each column. here you can find out if there are any NaN / NA values
#  Unique - what are the unique values in each column selected. like Gender male and female
#  top  - it displays the top row in the list of the data.
#  freq -  based on the top value (first row displayed) displayed above, it shows how frequent / number of occurance
#  the data is in the data. 

In [38]:
titanic_data[a].describe()

Name   Sex        Ticket        Cabin Embarked
count                   156   156           156           31      155
unique                  156     2           145           28        3
top     Kraeff, Mr. Theodor  male  S.O.C. 14879  C23 C25 C27        S
freq                      1   100             2            2      110

In [39]:
titanic_data.describe() #### when we call the describe function on the entire data frame, it will be default pick only those 
                        # column which have numerical values

PassengerId    Survived      Pclass         Age       SibSp  \
count   156.000000  156.000000  156.000000  126.000000  156.000000   
mean     78.500000    0.346154    2.423077   28.141508    0.615385   
std      45.177428    0.477275    0.795459   14.613880    1.056235   
min       1.000000    0.000000    1.000000    0.830000    0.000000   
25%      39.750000    0.000000    2.000000   19.000000    0.000000   
50%      78.500000    0.000000    3.000000   26.000000    0.000000   
75%     117.250000    1.000000    3.000000   35.000000    1.000000   
max     156.000000    1.000000    3.000000   71.000000    5.000000   

            Parch        Fare  
count  156.000000  156.000000  
mean     0.397436   28.109587  
std      0.870146   39.401047  
min      0.000000    6.750000  
25%      0.000000    8.003150  
50%      0.000000   14.454200  
75%      0.000000   30.371850  
max      5.000000  263.000000

In [49]:
sorted(titanic_data['Name'])

['Ahlin, Mrs. Johan (Johanna Persdotter Larsson)',
 'Allen, Mr. William Henry',
 'Andersson, Miss. Ellis Anna Maria',
 'Andersson, Miss. Erna Alexandra',
 'Andersson, Mr. Anders Johan',
 'Andersson, Mr. August Edvard ("Wennerstrom")',
 'Andreasson, Mr. Paul Edvin',
 'Andrew, Mr. Edgardo Samuel',
 'Arnold-Franchi, Mrs. Josef (Josefine Franchi)',
 'Asplund, Mrs. Carl Oscar (Selma Augusta Emilia Johansson)',
 'Attalah, Miss. Malake',
 'Backstrom, Mrs. Karl Alfred (Maria Mathilda Gustafsson)',
 'Barton, Mr. David John',
 'Bateman, Rev. Robert James',
 'Baxter, Mr. Quigg Edmond',
 'Beesley, Mr. Lawrence',
 'Bing, Mr. Lee',
 'Bonnell, Miss. Elizabeth',
 'Boulos, Mrs. Joseph (Sultana)',
 'Braund, Mr. Owen Harris',
 'Burke, Mr. Jeremiah',
 'Byles, Rev. Thomas Roussel Davids',
 'Caldwell, Master. Alden Gates',
 'Cann, Mr. Ernest Charles',
 'Carrau, Mr. Francisco M',
 'Celotti, Mr. Francesco',
 'Chaffee, Mr. Herbert Fuller',
 'Christmann, Mr. Emil',
 'Chronopoulos, Mr. Apostolos',
 'Coelho, Mr. 

In [50]:
titanic_data['Ticket'][4:9]  # displaing ticket values from 4th record till 8th record

4    373450
5    330877
6     17463
7    349909
8    347742
Name: Ticket, dtype: object

In [51]:
# to find out the column names availble in the data frame titanic_data
titanic_data.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [54]:
# to create a new column in your dataset. It first checks the in data if the column name is available or not. 
# If it is not available then it creates new else it will replace the values
titanic_data['test'] = 5 #  the value given to the whole column is 0. you can assign any value to entire column 

In [55]:
titanic_data.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  test  
0      0         A/5 21171   7.2500   NaN        S     5  
1      0          PC 17599  71.2833   C85        C     5  
2      0  STON/O2. 3101282   7.9250   NaN        S     5  
3      0            113803  53.1000  C123        S     5  
4      0            373450   8.0500   NaN        S     5

In [ ]:
# Renaming the categorical data

In [56]:
pd.Categorical(titanic_data['Pclass'])  # it shows, what are the categorical values available in Pclass(passenger class)

[3, 1, 3, 1, 3, ..., 1, 3, 3, 3, 1]
Length: 156
Categories (3, int64): [1, 2, 3]

In [59]:
# Now renaming the category present in Pclass
new_Pclass = pd.Categorical(titanic_data['Pclass'])
new_Pclass = new_Pclass.rename_categories(['c1','c2','c3'])
new_Pclass

[c3, c1, c3, c1, c3, ..., c1, c3, c3, c3, c1]
Length: 156
Categories (3, object): [c1, c2, c3]

In [64]:
titanic_data["Pclass"] = new_Pclass  # the new category for Pclass is changed in the titanic_data set

In [10]:
# renaming the categorgies in Sex column 
c_sex = pd.Categorical(titanic_data['Sex'])
c_sex=c_sex.rename_categories(['Male','Female'])
c_sex

[Female, Male, Male, Male, Female, ..., Male, Female, Female, Female, Female]
Length: 156
Categories (2, object): [Male, Female]

In [14]:
titanic_data.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [ ]:
# to find the unique values in the columns you can use this unique()

In [68]:
titanic_data["Cabin"].unique()  # here we do have the NaN values

array([nan, 'C85', 'C123', 'E46', 'G6', 'C103', 'D56', 'A6',
       'C23 C25 C27', 'B78', 'D33', 'B30', 'C52', 'B28', 'C83', 'F33',
       'F G73', 'E31', 'A5', 'D10 D12', 'D26', 'C110', 'B58 B60', 'E101',
       'F E69', 'D47', 'B86', 'F2', 'C2'], dtype=object)

In [69]:
titanic_data['Age'].isnull()  # checking if the age column has any null values

0      False
1      False
2      False
3      False
4      False
5       True
6      False
7      False
8      False
9      False
10     False
11     False
12     False
13     False
14     False
15     False
16     False
17      True
18     False
19      True
20     False
21     False
22     False
23     False
24     False
25     False
26      True
27     False
28      True
29      True
       ...  
126     True
127    False
128     True
129    False
130    False
131    False
132    False
133    False
134    False
135    False
136    False
137    False
138    False
139    False
140     True
141    False
142    False
143    False
144    False
145    False
146    False
147    False
148    False
149    False
150    False
151    False
152    False
153    False
154     True
155    False
Name: Age, Length: 156, dtype: bool

In [5]:
import numpy as np  # importing numpy library to use where i.e. for filtering

In [71]:
missing_age = np.where(titanic_data['Age'].isnull() == True) # where returns the index number of the value/column 

In [72]:
missing_age     # showing the index numbers of Age column where the null value is true

(array([  5,  17,  19,  26,  28,  29,  31,  32,  36,  42,  45,  46,  47,
         48,  55,  64,  65,  76,  77,  82,  87,  95, 101, 107, 109, 121,
        126, 128, 140, 154], dtype=int64),)

In [73]:
np.where(titanic_data['Fare']==max(titanic_data['Fare']))

(array([27, 88], dtype=int64),)

In [76]:
# since where gives the index numbers, we need to use iloc and it needs to be given in square brackets
# Here the output shows the rows which has the max fare rate in the data
titanic_data.iloc[np.where(titanic_data['Fare']==max(titanic_data['Fare']))]

PassengerId  Survived Pclass                            Name     Sex  \
27           28         0     c1  Fortune, Mr. Charles Alexander    male   
88           89         1     c1      Fortune, Miss. Mabel Helen  female   

     Age  SibSp  Parch Ticket   Fare        Cabin Embarked  test  
27  19.0      3      2  19950  263.0  C23 C25 C27        S     5  
88  23.0      3      2  19950  263.0  C23 C25 C27        S     5

In [18]:
np.where((titanic_data['Age'] == 22)  & (titanic_data['Sex'] == 'female'))

(array([141, 151], dtype=int64),)

In [16]:
titanic_data.iloc[np.where((titanic_data['Age'] == 22)  & (titanic_data['Sex'] == 'female'))]

PassengerId  Survived  Pclass                               Name     Sex  \
141          142         1       3           Nysten, Miss. Anna Sofia  female   
151          152         1       1  Pears, Mrs. Thomas (Edith Wearne)  female   

      Age  SibSp  Parch  Ticket   Fare Cabin Embarked  
141  22.0      0      0  347081   7.75   NaN        S  
151  22.0      1      0  113776  66.60    C2        S